#!/bin/sh -e

case "$1" in
  purge)
  rm -f /etc/modules
  ;;
esac

# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d kmod remove >/dev/null
fi
# End automatically added section


exit 0
